// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_me_ap_fixed_ap_fixed_32_16_5_3_0_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [31:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_V_read;
reg[31:0] res_V_V_din;
reg res_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [3199:0] layer_in_V_21;
reg   [31:0] sX_9;
reg   [31:0] sY_9;
reg   [31:0] pY_9;
reg   [31:0] pX_9;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg   [0:0] and_ln215_4_reg_875;
reg   [31:0] tmp_V_reg_823;
reg   [31:0] tmp_V_130_reg_828;
reg   [31:0] tmp_V_131_reg_833;
reg   [31:0] tmp_V_132_reg_838;
reg   [31:0] sX_9_load_reg_843;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln215_fu_594_p2;
reg   [0:0] icmp_ln215_reg_848;
reg   [31:0] sY_9_load_reg_853;
wire   [0:0] icmp_ln215_4_fu_604_p2;
reg   [0:0] icmp_ln215_4_reg_858;
reg   [31:0] pY_9_load_reg_863;
reg   [31:0] pX_9_load_reg_869;
wire   [0:0] and_ln215_4_fu_662_p2;
wire   [11:0] i_fu_668_p2;
reg   [11:0] i_reg_879;
wire   [19:0] add_ln411_fu_674_p2;
wire    ap_CS_fsm_state8;
wire   [9:0] ir_fu_720_p2;
wire   [0:0] icmp_ln237_fu_732_p2;
reg   [0:0] icmp_ln237_reg_900;
reg    ap_block_state16;
wire   [31:0] select_ln252_fu_753_p3;
reg   [31:0] select_ln252_reg_904;
wire   [0:0] icmp_ln241_fu_772_p2;
reg   [0:0] icmp_ln241_reg_909;
wire   [31:0] select_ln247_fu_793_p3;
reg   [31:0] select_ln247_reg_913;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_done;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_idle;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_ready;
wire   [127:0] grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_data_V_read;
wire   [3199:0] grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_return;
reg   [11:0] i_0_i18_reg_151;
reg    ap_block_state1;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln206_fu_817_p2;
reg   [9:0] ir1_0_i_i_i17_reg_163;
wire   [0:0] icmp_ln404_fu_726_p2;
reg   [31:0] tmp_V_13316_reg_174;
reg   [31:0] ap_phi_mux_tmp_V_133_phi_fu_495_p16;
reg   [31:0] tmp_V_13414_reg_185;
reg   [31:0] ap_phi_mux_tmp_V_134_phi_fu_464_p16;
reg   [31:0] tmp_V_13512_reg_196;
reg   [31:0] ap_phi_mux_tmp_V_135_phi_fu_433_p16;
reg   [31:0] tmp_V_13610_reg_207;
reg   [31:0] ap_phi_mux_tmp_V_136_phi_fu_402_p16;
reg   [31:0] tmp_V_1378_reg_218;
reg   [31:0] ap_phi_mux_tmp_V_137_phi_fu_371_p16;
reg   [31:0] tmp_V_1386_reg_229;
reg   [31:0] ap_phi_mux_tmp_V_138_phi_fu_340_p16;
reg   [31:0] tmp_V_1394_reg_240;
reg   [31:0] ap_phi_mux_tmp_V_139_phi_fu_309_p16;
reg   [31:0] tmp_V_1402_reg_251;
reg   [31:0] ap_phi_mux_tmp_V_140_phi_fu_278_p16;
reg   [19:0] phi_mul_reg_262;
wire   [31:0] acc_0_V_fu_690_p10;
reg   [31:0] tmp_V_140_reg_273;
wire   [2:0] trunc_ln_fu_680_p4;
reg   [31:0] tmp_V_139_reg_304;
reg   [31:0] tmp_V_138_reg_335;
reg   [31:0] tmp_V_137_reg_366;
reg   [31:0] tmp_V_136_reg_397;
reg   [31:0] tmp_V_135_reg_428;
reg   [31:0] tmp_V_134_reg_459;
reg   [31:0] tmp_V_133_reg_490;
reg   [31:0] ap_phi_mux_storemerge_i_phi_fu_525_p4;
reg   [31:0] storemerge_i_reg_521;
reg    grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start_reg;
reg   [16:0] ap_NS_fsm;
wire    ap_NS_fsm_state6;
wire    ap_CS_fsm_state6;
wire   [31:0] add_ln245_fu_777_p2;
wire   [31:0] add_ln250_fu_737_p2;
wire   [29:0] tmp_31_fu_614_p4;
wire   [29:0] tmp_32_fu_634_p4;
wire   [0:0] icmp_ln215_5_fu_624_p2;
wire   [0:0] icmp_ln215_6_fu_644_p2;
wire   [0:0] and_ln215_3_fu_656_p2;
wire   [0:0] and_ln215_fu_650_p2;
wire   [2:0] acc_0_V_fu_690_p9;
wire   [31:0] add_ln252_fu_748_p2;
wire   [31:0] add_ln247_fu_788_p2;
reg    ap_condition_189;
reg    ap_condition_198;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 17'd1;
#0 layer_in_V_21 = 3200'd0;
#0 sX_9 = 32'd0;
#0 sY_9 = 32'd0;
#0 pY_9 = 32'd0;
#0 pX_9 = 32'd0;
#0 grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start_reg = 1'b0;
end

cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start),
    .ap_done(grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_done),
    .ap_idle(grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_idle),
    .ap_ready(grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_ready),
    .data_V_read(grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_data_V_read),
    .output_V_read(layer_in_V_21),
    .ap_return(grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_return)
);

myproject_axi_mux_83_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
myproject_axi_mux_83_32_1_1_U21(
    .din0(tmp_V_13316_reg_174),
    .din1(tmp_V_13414_reg_185),
    .din2(tmp_V_13512_reg_196),
    .din3(tmp_V_13610_reg_207),
    .din4(tmp_V_1378_reg_218),
    .din5(tmp_V_1386_reg_229),
    .din6(tmp_V_1394_reg_240),
    .din7(tmp_V_1402_reg_251),
    .din8(acc_0_V_fu_690_p9),
    .dout(acc_0_V_fu_690_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln206_fu_817_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (1'b1 == ap_NS_fsm_state6))) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start_reg <= 1'b1;
        end else if ((grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_ready == 1'b1)) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln206_fu_817_p2 == 1'd0))) begin
        i_0_i18_reg_151 <= i_reg_879;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i18_reg_151 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        ir1_0_i_i_i17_reg_163 <= ir_fu_720_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        ir1_0_i_i_i17_reg_163 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_189)) begin
        if ((icmp_ln237_fu_732_p2 == 1'd1)) begin
            pX_9 <= 32'd0;
        end else if ((icmp_ln237_fu_732_p2 == 1'd0)) begin
            pX_9 <= add_ln250_fu_737_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_198)) begin
        if ((icmp_ln241_fu_772_p2 == 1'd1)) begin
            pY_9 <= 32'd0;
        end else if ((icmp_ln241_fu_772_p2 == 1'd0)) begin
            pY_9 <= add_ln245_fu_777_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        phi_mul_reg_262 <= add_ln411_fu_674_p2;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        phi_mul_reg_262 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln237_reg_900 == 1'd0))) begin
        sX_9 <= select_ln252_reg_904;
    end else if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (icmp_ln237_fu_732_p2 == 1'd1))) begin
        sX_9 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (icmp_ln241_fu_772_p2 == 1'd1) & (icmp_ln237_fu_732_p2 == 1'd1))) begin
        storemerge_i_reg_521 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln241_reg_909 == 1'd0) & (icmp_ln237_reg_900 == 1'd1))) begin
        storemerge_i_reg_521 <= select_ln247_reg_913;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_13316_reg_174 <= ap_phi_mux_tmp_V_133_phi_fu_495_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_13316_reg_174 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_133_reg_490 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_133_reg_490 <= tmp_V_13316_reg_174;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_13414_reg_185 <= ap_phi_mux_tmp_V_134_phi_fu_464_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_13414_reg_185 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_134_reg_459 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_134_reg_459 <= tmp_V_13414_reg_185;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_13512_reg_196 <= ap_phi_mux_tmp_V_135_phi_fu_433_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_13512_reg_196 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_135_reg_428 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_135_reg_428 <= tmp_V_13512_reg_196;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_13610_reg_207 <= ap_phi_mux_tmp_V_136_phi_fu_402_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_13610_reg_207 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_136_reg_397 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_136_reg_397 <= tmp_V_13610_reg_207;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_1378_reg_218 <= ap_phi_mux_tmp_V_137_phi_fu_371_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_1378_reg_218 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_137_reg_366 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_137_reg_366 <= tmp_V_1378_reg_218;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_1386_reg_229 <= ap_phi_mux_tmp_V_138_phi_fu_340_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_1386_reg_229 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_138_reg_335 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_138_reg_335 <= tmp_V_1386_reg_229;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_1394_reg_240 <= ap_phi_mux_tmp_V_139_phi_fu_309_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_1394_reg_240 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_139_reg_304 <= acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_139_reg_304 <= tmp_V_1394_reg_240;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
        tmp_V_1402_reg_251 <= ap_phi_mux_tmp_V_140_phi_fu_278_p16;
    end else if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
        tmp_V_1402_reg_251 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)))) begin
        tmp_V_140_reg_273 <= tmp_V_1402_reg_251;
    end else if (((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_140_reg_273 <= acc_0_V_fu_690_p10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        and_ln215_4_reg_875 <= and_ln215_4_fu_662_p2;
        i_reg_879 <= i_fu_668_p2;
        icmp_ln215_4_reg_858 <= icmp_ln215_4_fu_604_p2;
        icmp_ln215_reg_848 <= icmp_ln215_fu_594_p2;
        layer_in_V_21 <= grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_return;
        pX_9_load_reg_869 <= pX_9;
        pY_9_load_reg_863 <= pY_9;
        sX_9_load_reg_843 <= sX_9;
        sY_9_load_reg_853 <= sY_9;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16))) begin
        icmp_ln237_reg_900 <= icmp_ln237_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (icmp_ln237_fu_732_p2 == 1'd1))) begin
        icmp_ln241_reg_909 <= icmp_ln241_fu_772_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln237_reg_900 == 1'd1))) begin
        sY_9 <= ap_phi_mux_storemerge_i_phi_fu_525_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (icmp_ln241_fu_772_p2 == 1'd0) & (icmp_ln237_fu_732_p2 == 1'd1))) begin
        select_ln247_reg_913 <= select_ln247_fu_793_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (icmp_ln237_fu_732_p2 == 1'd0))) begin
        select_ln252_reg_904 <= select_ln252_fu_753_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_V_130_reg_828 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_V_131_reg_833 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_V_132_reg_838 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_V_reg_823 <= data_V_V_dout;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln206_fu_817_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln241_reg_909 == 1'd0) & (icmp_ln237_reg_900 == 1'd1))) begin
        ap_phi_mux_storemerge_i_phi_fu_525_p4 = select_ln247_reg_913;
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_525_p4 = storemerge_i_reg_521;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_133_phi_fu_495_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_133_phi_fu_495_p16 = tmp_V_13316_reg_174;
    end else begin
        ap_phi_mux_tmp_V_133_phi_fu_495_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_134_phi_fu_464_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_134_phi_fu_464_p16 = tmp_V_13414_reg_185;
    end else begin
        ap_phi_mux_tmp_V_134_phi_fu_464_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_135_phi_fu_433_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_135_phi_fu_433_p16 = tmp_V_13512_reg_196;
    end else begin
        ap_phi_mux_tmp_V_135_phi_fu_433_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_136_phi_fu_402_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_136_phi_fu_402_p16 = tmp_V_13610_reg_207;
    end else begin
        ap_phi_mux_tmp_V_136_phi_fu_402_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_137_phi_fu_371_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_137_phi_fu_371_p16 = tmp_V_1378_reg_218;
    end else begin
        ap_phi_mux_tmp_V_137_phi_fu_371_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_138_phi_fu_340_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_138_phi_fu_340_p16 = tmp_V_1386_reg_229;
    end else begin
        ap_phi_mux_tmp_V_138_phi_fu_340_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_139_phi_fu_309_p16 = acc_0_V_fu_690_p10;
    end else if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_139_phi_fu_309_p16 = tmp_V_1394_reg_240;
    end else begin
        ap_phi_mux_tmp_V_139_phi_fu_309_p16 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln_fu_680_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state8)) | ((trunc_ln_fu_680_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state8)))) begin
        ap_phi_mux_tmp_V_140_phi_fu_278_p16 = tmp_V_1402_reg_251;
    end else if (((trunc_ln_fu_680_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_phi_mux_tmp_V_140_phi_fu_278_p16 = acc_0_V_fu_690_p10;
    end else begin
        ap_phi_mux_tmp_V_140_phi_fu_278_p16 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln206_fu_817_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | ((1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln215_4_reg_875)))) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln215_4_reg_875))) begin
        res_V_V_din = tmp_V_140_reg_273;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        res_V_V_din = tmp_V_139_reg_304;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        res_V_V_din = tmp_V_138_reg_335;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        res_V_V_din = tmp_V_137_reg_366;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        res_V_V_din = tmp_V_136_reg_397;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
        res_V_V_din = tmp_V_135_reg_428;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        res_V_V_din = tmp_V_134_reg_459;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        res_V_V_din = tmp_V_133_reg_490;
    end else begin
        res_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | (~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (1'd1 == and_ln215_4_reg_875)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (1'd1 == and_ln215_4_fu_662_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (icmp_ln404_fu_726_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == ap_CS_fsm_state17) & (icmp_ln206_fu_817_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_690_p9 = {{phi_mul_reg_262[19:17]}};

assign add_ln245_fu_777_p2 = (pY_9_load_reg_863 + 32'd1);

assign add_ln247_fu_788_p2 = (sY_9_load_reg_853 + 32'd1);

assign add_ln250_fu_737_p2 = (pX_9_load_reg_869 + 32'd1);

assign add_ln252_fu_748_p2 = (sX_9_load_reg_843 + 32'd1);

assign add_ln411_fu_674_p2 = (phi_mul_reg_262 + 20'd1311);

assign and_ln215_3_fu_656_p2 = (icmp_ln215_6_fu_644_p2 & icmp_ln215_5_fu_624_p2);

assign and_ln215_4_fu_662_p2 = (and_ln215_fu_650_p2 & and_ln215_3_fu_656_p2);

assign and_ln215_fu_650_p2 = (icmp_ln215_fu_594_p2 & icmp_ln215_4_fu_604_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state6 = ap_NS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state16 = ((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875));
end

always @ (*) begin
    ap_condition_189 = (~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16));
end

always @ (*) begin
    ap_condition_198 = (~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_4_reg_875)) & (1'b1 == ap_CS_fsm_state16) & (icmp_ln237_fu_732_p2 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start = grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_ap_start_reg;

assign grp_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config4_s_fu_532_data_V_read = {{{{tmp_V_132_reg_838}, {tmp_V_131_reg_833}}, {tmp_V_130_reg_828}}, {tmp_V_reg_823}};

assign i_fu_668_p2 = (i_0_i18_reg_151 + 12'd1);

assign icmp_ln206_fu_817_p2 = ((i_0_i18_reg_151 == 12'd3539) ? 1'b1 : 1'b0);

assign icmp_ln215_4_fu_604_p2 = ((sY_9 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln215_5_fu_624_p2 = (($signed(tmp_31_fu_614_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln215_6_fu_644_p2 = (($signed(tmp_32_fu_634_p4) > $signed(30'd0)) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_594_p2 = ((sX_9 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_732_p2 = ((pX_9_load_reg_869 == 32'd58) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_772_p2 = ((pY_9_load_reg_863 == 32'd59) ? 1'b1 : 1'b0);

assign icmp_ln404_fu_726_p2 = ((ir1_0_i_i_i17_reg_163 == 10'd799) ? 1'b1 : 1'b0);

assign ir_fu_720_p2 = (ir1_0_i_i_i17_reg_163 + 10'd1);

assign select_ln247_fu_793_p3 = ((icmp_ln215_4_reg_858[0:0] === 1'b1) ? 32'd4 : add_ln247_fu_788_p2);

assign select_ln252_fu_753_p3 = ((icmp_ln215_reg_848[0:0] === 1'b1) ? 32'd4 : add_ln252_fu_748_p2);

assign start_out = real_start;

assign tmp_31_fu_614_p4 = {{pY_9[31:2]}};

assign tmp_32_fu_634_p4 = {{pX_9[31:2]}};

assign trunc_ln_fu_680_p4 = {{phi_mul_reg_262[19:17]}};

endmodule //conv_2d_cl_me_ap_fixed_ap_fixed_32_16_5_3_0_config4_s
