// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_me_ap_fixed_ap_fixed_32_16_5_3_0_config22_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [31:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_V_read;
reg[31:0] res_V_V_din;
reg res_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [2303:0] layer_in_V_14;
reg   [31:0] sX_1;
reg   [31:0] sY_1;
reg   [31:0] pY_1;
reg   [31:0] pX_1;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg   [0:0] and_ln215_14_reg_897;
reg   [31:0] tmp_V_reg_825;
reg   [31:0] tmp_V_201_reg_830;
reg   [31:0] tmp_V_202_reg_835;
reg   [31:0] tmp_V_203_reg_840;
reg   [31:0] tmp_V_204_reg_845;
reg   [31:0] tmp_V_205_reg_850;
reg   [31:0] tmp_V_206_reg_855;
reg   [31:0] tmp_V_207_reg_860;
reg   [31:0] sX_1_load_reg_865;
wire    ap_CS_fsm_state10;
wire   [0:0] icmp_ln215_fu_596_p2;
reg   [0:0] icmp_ln215_reg_870;
reg   [31:0] sY_1_load_reg_875;
wire   [0:0] icmp_ln215_19_fu_606_p2;
reg   [0:0] icmp_ln215_19_reg_880;
reg   [31:0] pY_1_load_reg_885;
reg   [31:0] pX_1_load_reg_891;
wire   [0:0] and_ln215_14_fu_664_p2;
wire   [7:0] i_fu_670_p2;
reg   [7:0] i_reg_901;
wire   [19:0] add_ln411_fu_676_p2;
wire    ap_CS_fsm_state11;
wire   [9:0] ir_fu_722_p2;
wire   [0:0] icmp_ln237_fu_734_p2;
reg   [0:0] icmp_ln237_reg_922;
reg    ap_block_state19;
wire   [31:0] select_ln252_fu_755_p3;
reg   [31:0] select_ln252_reg_926;
wire   [0:0] icmp_ln241_fu_774_p2;
reg   [0:0] icmp_ln241_reg_931;
wire   [31:0] select_ln247_fu_795_p3;
reg   [31:0] select_ln247_reg_935;
reg    call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_start;
wire    call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_done;
wire    call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_idle;
wire    call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_ready;
wire   [255:0] call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_data_V_read;
wire   [2303:0] call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_return;
reg   [7:0] i_0_i18_reg_149;
reg    ap_block_state1;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln206_fu_819_p2;
reg   [9:0] ir1_0_i_i_i17_reg_161;
wire   [0:0] icmp_ln404_fu_728_p2;
reg   [31:0] tmp_V_17316_reg_172;
reg   [31:0] ap_phi_mux_tmp_V_208_phi_fu_493_p16;
reg   [31:0] tmp_V_17414_reg_183;
reg   [31:0] ap_phi_mux_tmp_V_209_phi_fu_462_p16;
reg   [31:0] tmp_V_17512_reg_194;
reg   [31:0] ap_phi_mux_tmp_V_210_phi_fu_431_p16;
reg   [31:0] tmp_V_17610_reg_205;
reg   [31:0] ap_phi_mux_tmp_V_211_phi_fu_400_p16;
reg   [31:0] tmp_V_1778_reg_216;
reg   [31:0] ap_phi_mux_tmp_V_212_phi_fu_369_p16;
reg   [31:0] tmp_V_1786_reg_227;
reg   [31:0] ap_phi_mux_tmp_V_213_phi_fu_338_p16;
reg   [31:0] tmp_V_1794_reg_238;
reg   [31:0] ap_phi_mux_tmp_V_214_phi_fu_307_p16;
reg   [31:0] tmp_V_1802_reg_249;
reg   [31:0] ap_phi_mux_tmp_V_215_phi_fu_276_p16;
reg   [19:0] phi_mul_reg_260;
wire   [31:0] acc_0_V_fu_692_p10;
reg   [31:0] tmp_V_215_reg_271;
wire   [2:0] trunc_ln_fu_682_p4;
reg   [31:0] tmp_V_214_reg_302;
reg   [31:0] tmp_V_213_reg_333;
reg   [31:0] tmp_V_212_reg_364;
reg   [31:0] tmp_V_211_reg_395;
reg   [31:0] tmp_V_210_reg_426;
reg   [31:0] tmp_V_209_reg_457;
reg   [31:0] tmp_V_208_reg_488;
reg   [31:0] ap_phi_mux_storemerge_i_phi_fu_523_p4;
reg   [31:0] storemerge_i_reg_519;
wire   [31:0] add_ln245_fu_779_p2;
wire   [31:0] add_ln250_fu_739_p2;
wire   [30:0] tmp_41_fu_616_p4;
wire   [30:0] tmp_42_fu_636_p4;
wire   [0:0] icmp_ln215_20_fu_626_p2;
wire   [0:0] icmp_ln215_21_fu_646_p2;
wire   [0:0] and_ln215_13_fu_658_p2;
wire   [0:0] and_ln215_fu_652_p2;
wire   [2:0] acc_0_V_fu_692_p9;
wire   [31:0] add_ln252_fu_750_p2;
wire   [31:0] add_ln247_fu_790_p2;
reg   [19:0] ap_NS_fsm;
reg    ap_condition_224;
reg    ap_condition_233;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 20'd1;
#0 layer_in_V_14 = 2304'd0;
#0 sX_1 = 32'd0;
#0 sY_1 = 32'd0;
#0 pY_1 = 32'd0;
#0 pX_1 = 32'd0;
end

cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_start),
    .ap_done(call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_done),
    .ap_idle(call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_idle),
    .ap_ready(call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_ready),
    .data_V_read(call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_data_V_read),
    .output_V_read(layer_in_V_14),
    .ap_return(call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_return)
);

myproject_axi_mux_83_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
myproject_axi_mux_83_32_1_1_U101(
    .din0(tmp_V_17316_reg_172),
    .din1(tmp_V_17414_reg_183),
    .din2(tmp_V_17512_reg_194),
    .din3(tmp_V_17610_reg_205),
    .din4(tmp_V_1778_reg_216),
    .din5(tmp_V_1786_reg_227),
    .din6(tmp_V_1794_reg_238),
    .din7(tmp_V_1802_reg_249),
    .din8(acc_0_V_fu_692_p9),
    .dout(acc_0_V_fu_692_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln206_fu_819_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln206_fu_819_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        i_0_i18_reg_149 <= i_reg_901;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i18_reg_149 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        ir1_0_i_i_i17_reg_161 <= ir_fu_722_p2;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        ir1_0_i_i_i17_reg_161 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_224)) begin
        if ((icmp_ln237_fu_734_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln237_fu_734_p2 == 1'd0)) begin
            pX_1 <= add_ln250_fu_739_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_233)) begin
        if ((icmp_ln241_fu_774_p2 == 1'd1)) begin
            pY_1 <= 32'd0;
        end else if ((icmp_ln241_fu_774_p2 == 1'd0)) begin
            pY_1 <= add_ln245_fu_779_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        phi_mul_reg_260 <= add_ln411_fu_676_p2;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        phi_mul_reg_260 <= 20'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln237_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        sX_1 <= select_ln252_reg_926;
    end else if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln237_fu_734_p2 == 1'd1))) begin
        sX_1 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln241_fu_774_p2 == 1'd1) & (icmp_ln237_fu_734_p2 == 1'd1))) begin
        storemerge_i_reg_519 <= 32'd0;
    end else if (((icmp_ln241_reg_931 == 1'd0) & (1'b1 == ap_CS_fsm_state20) & (icmp_ln237_reg_922 == 1'd1))) begin
        storemerge_i_reg_519 <= select_ln247_reg_935;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_17316_reg_172 <= ap_phi_mux_tmp_V_208_phi_fu_493_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_17316_reg_172 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_17414_reg_183 <= ap_phi_mux_tmp_V_209_phi_fu_462_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_17414_reg_183 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_17512_reg_194 <= ap_phi_mux_tmp_V_210_phi_fu_431_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_17512_reg_194 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_17610_reg_205 <= ap_phi_mux_tmp_V_211_phi_fu_400_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_17610_reg_205 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_1778_reg_216 <= ap_phi_mux_tmp_V_212_phi_fu_369_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_1778_reg_216 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_1786_reg_227 <= ap_phi_mux_tmp_V_213_phi_fu_338_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_1786_reg_227 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_1794_reg_238 <= ap_phi_mux_tmp_V_214_phi_fu_307_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_1794_reg_238 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_1802_reg_249 <= ap_phi_mux_tmp_V_215_phi_fu_276_p16;
    end else if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
        tmp_V_1802_reg_249 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_208_reg_488 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_208_reg_488 <= tmp_V_17316_reg_172;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_209_reg_457 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_209_reg_457 <= tmp_V_17414_reg_183;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_210_reg_426 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_210_reg_426 <= tmp_V_17512_reg_194;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_211_reg_395 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_211_reg_395 <= tmp_V_17610_reg_205;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_212_reg_364 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_212_reg_364 <= tmp_V_1778_reg_216;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_213_reg_333 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_213_reg_333 <= tmp_V_1786_reg_227;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_214_reg_302 <= acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_214_reg_302 <= tmp_V_1794_reg_238;
    end
end

always @ (posedge ap_clk) begin
    if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)))) begin
        tmp_V_215_reg_271 <= tmp_V_1802_reg_249;
    end else if (((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_V_215_reg_271 <= acc_0_V_fu_692_p10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        and_ln215_14_reg_897 <= and_ln215_14_fu_664_p2;
        i_reg_901 <= i_fu_670_p2;
        icmp_ln215_19_reg_880 <= icmp_ln215_19_fu_606_p2;
        icmp_ln215_reg_870 <= icmp_ln215_fu_596_p2;
        layer_in_V_14 <= call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_return;
        pX_1_load_reg_891 <= pX_1;
        pY_1_load_reg_885 <= pY_1;
        sX_1_load_reg_865 <= sX_1;
        sY_1_load_reg_875 <= sY_1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19))) begin
        icmp_ln237_reg_922 <= icmp_ln237_fu_734_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln237_fu_734_p2 == 1'd1))) begin
        icmp_ln241_reg_931 <= icmp_ln241_fu_774_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln237_reg_922 == 1'd1))) begin
        sY_1 <= ap_phi_mux_storemerge_i_phi_fu_523_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (icmp_ln241_fu_774_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln237_fu_734_p2 == 1'd1))) begin
        select_ln247_reg_935 <= select_ln247_fu_795_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (icmp_ln237_fu_734_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state19))) begin
        select_ln252_reg_926 <= select_ln252_fu_755_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_V_201_reg_830 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_V_202_reg_835 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_V_203_reg_840 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_V_204_reg_845 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_V_205_reg_850 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        tmp_V_206_reg_855 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        tmp_V_207_reg_860 <= data_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_V_reg_825 <= data_V_V_dout;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln206_fu_819_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_931 == 1'd0) & (1'b1 == ap_CS_fsm_state20) & (icmp_ln237_reg_922 == 1'd1))) begin
        ap_phi_mux_storemerge_i_phi_fu_523_p4 = select_ln247_reg_935;
    end else begin
        ap_phi_mux_storemerge_i_phi_fu_523_p4 = storemerge_i_reg_519;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_208_phi_fu_493_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_208_phi_fu_493_p16 = tmp_V_17316_reg_172;
    end else begin
        ap_phi_mux_tmp_V_208_phi_fu_493_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_209_phi_fu_462_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_209_phi_fu_462_p16 = tmp_V_17414_reg_183;
    end else begin
        ap_phi_mux_tmp_V_209_phi_fu_462_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_210_phi_fu_431_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_210_phi_fu_431_p16 = tmp_V_17512_reg_194;
    end else begin
        ap_phi_mux_tmp_V_210_phi_fu_431_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_211_phi_fu_400_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_211_phi_fu_400_p16 = tmp_V_17610_reg_205;
    end else begin
        ap_phi_mux_tmp_V_211_phi_fu_400_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_212_phi_fu_369_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_212_phi_fu_369_p16 = tmp_V_1778_reg_216;
    end else begin
        ap_phi_mux_tmp_V_212_phi_fu_369_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_213_phi_fu_338_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_213_phi_fu_338_p16 = tmp_V_1786_reg_227;
    end else begin
        ap_phi_mux_tmp_V_213_phi_fu_338_p16 = 'bx;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_214_phi_fu_307_p16 = acc_0_V_fu_692_p10;
    end else if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_214_phi_fu_307_p16 = tmp_V_1794_reg_238;
    end else begin
        ap_phi_mux_tmp_V_214_phi_fu_307_p16 = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln_fu_682_p4 == 3'd0) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd1) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd2) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd3) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd4) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd5) & (1'b1 == ap_CS_fsm_state11)) | ((trunc_ln_fu_682_p4 == 3'd6) & (1'b1 == ap_CS_fsm_state11)))) begin
        ap_phi_mux_tmp_V_215_phi_fu_276_p16 = tmp_V_1802_reg_249;
    end else if (((trunc_ln_fu_682_p4 == 3'd7) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_tmp_V_215_phi_fu_276_p16 = acc_0_V_fu_692_p10;
    end else begin
        ap_phi_mux_tmp_V_215_phi_fu_276_p16 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_start = 1'b1;
    end else begin
        call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln206_fu_819_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state19) & (1'd1 == and_ln215_14_reg_897)))) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19) & (1'd1 == and_ln215_14_reg_897))) begin
        res_V_V_din = tmp_V_215_reg_271;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        res_V_V_din = tmp_V_214_reg_302;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        res_V_V_din = tmp_V_213_reg_333;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        res_V_V_din = tmp_V_212_reg_364;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        res_V_V_din = tmp_V_211_reg_395;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        res_V_V_din = tmp_V_210_reg_426;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        res_V_V_din = tmp_V_209_reg_457;
    end else if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        res_V_V_din = tmp_V_208_reg_488;
    end else begin
        res_V_V_din = 'bx;
    end
end

always @ (*) begin
    if (((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19) & (1'd1 == and_ln215_14_reg_897)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((data_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == and_ln215_14_fu_664_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((icmp_ln404_fu_728_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if ((~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln206_fu_819_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_692_p9 = {{phi_mul_reg_260[19:17]}};

assign add_ln245_fu_779_p2 = (pY_1_load_reg_885 + 32'd1);

assign add_ln247_fu_790_p2 = (sY_1_load_reg_875 + 32'd1);

assign add_ln250_fu_739_p2 = (pX_1_load_reg_891 + 32'd1);

assign add_ln252_fu_750_p2 = (sX_1_load_reg_865 + 32'd1);

assign add_ln411_fu_676_p2 = (phi_mul_reg_260 + 20'd1821);

assign and_ln215_13_fu_658_p2 = (icmp_ln215_21_fu_646_p2 & icmp_ln215_20_fu_626_p2);

assign and_ln215_14_fu_664_p2 = (and_ln215_fu_652_p2 & and_ln215_13_fu_658_p2);

assign and_ln215_fu_652_p2 = (icmp_ln215_fu_596_p2 & icmp_ln215_19_fu_606_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state19 = ((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897));
end

always @ (*) begin
    ap_condition_224 = (~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19));
end

always @ (*) begin
    ap_condition_233 = (~((res_V_V_full_n == 1'b0) & (1'd1 == and_ln215_14_reg_897)) & (1'b1 == ap_CS_fsm_state19) & (icmp_ln237_fu_734_p2 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign call_ret_cnnshift_arr_ap_fixed_ap_fixed_32_16_5_3_0_config22_s_fu_530_data_V_read = {{{{{{{{tmp_V_207_reg_860}, {tmp_V_206_reg_855}}, {tmp_V_205_reg_850}}, {tmp_V_204_reg_845}}, {tmp_V_203_reg_840}}, {tmp_V_202_reg_835}}, {tmp_V_201_reg_830}}, {tmp_V_reg_825}};

assign i_fu_670_p2 = (i_0_i18_reg_149 + 8'd1);

assign icmp_ln206_fu_819_p2 = ((i_0_i18_reg_149 == 8'd239) ? 1'b1 : 1'b0);

assign icmp_ln215_19_fu_606_p2 = ((sY_1 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln215_20_fu_626_p2 = (($signed(tmp_41_fu_616_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln215_21_fu_646_p2 = (($signed(tmp_42_fu_636_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_596_p2 = ((sX_1 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_734_p2 = ((pX_1_load_reg_891 == 32'd14) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_774_p2 = ((pY_1_load_reg_885 == 32'd15) ? 1'b1 : 1'b0);

assign icmp_ln404_fu_728_p2 = ((ir1_0_i_i_i17_reg_161 == 10'd575) ? 1'b1 : 1'b0);

assign ir_fu_722_p2 = (ir1_0_i_i_i17_reg_161 + 10'd1);

assign select_ln247_fu_795_p3 = ((icmp_ln215_19_reg_880[0:0] === 1'b1) ? 32'd2 : add_ln247_fu_790_p2);

assign select_ln252_fu_755_p3 = ((icmp_ln215_reg_870[0:0] === 1'b1) ? 32'd2 : add_ln252_fu_750_p2);

assign start_out = real_start;

assign tmp_41_fu_616_p4 = {{pY_1[31:1]}};

assign tmp_42_fu_636_p4 = {{pX_1[31:1]}};

assign trunc_ln_fu_682_p4 = {{phi_mul_reg_260[19:17]}};

endmodule //conv_2d_cl_me_ap_fixed_ap_fixed_32_16_5_3_0_config22_s
